// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    VirtualizedCheckGroupSelector: typeof import('./src/components/VirtualizedCheckGroupSelector/index.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/index.vue')['default']
    VirtualListWithFilter: typeof import('./src/components/VirtualListWithFilter/index.vue')['default']
  }
}
